### PR TITLE
Feat - added login page

### PR DESCRIPTION
**Pull request by Mohasin-Haque**
* Added Login page for e-com.
 * See the preview here: - https://deploy-preview-4--fast-cart.netlify.app/
 
 
image

### CODE REVIEW

**Review by chanchal-panpaliya — COMMENTED** [review]
The overall code is good - units , class name , layout tag. No need to change.

**Review by saifudinbadani — APPROVED** [review]
Looks good.

**Review by RakshaPawar108 — APPROVED** [review]
The code looks clean and good to merge. Great work with the UI as well!

**Review by Rishi05051997 — COMMENTED** [review]
Look Good merge it

**Pull request merged**
